"""change in name

Revision ID: aed6cd7294d3
Revises: f6c02030802e
Create Date: 2020-12-22 16:57:05.799038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed6cd7294d3'
down_revision = 'f6c02030802e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('date_of_apply', sa.DateTime(), nullable=True),
    sa.Column('urea', sa.Integer(), nullable=True),
    sa.Column('dap', sa.Integer(), nullable=True),
    sa.Column('ammonium_sulphate', sa.Integer(), nullable=True),
    sa.Column('bag_of_12X32X16', sa.Integer(), nullable=True),
    sa.Column('bag_of_10X26X26', sa.Integer(), nullable=True),
    sa.Column('mop', sa.Integer(), nullable=True),
    sa.Column('micronutrients', sa.Integer(), nullable=True),
    sa.Column('sulphur', sa.Integer(), nullable=True),
    sa.Column('bag_of_19X19X19', sa.Integer(), nullable=True),
    sa.Column('bag_of_20X20X0X13', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fretilizers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fretilizers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crop_id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_apply', sa.DATETIME(), nullable=True),
    sa.Column('urea', sa.INTEGER(), nullable=True),
    sa.Column('dap', sa.INTEGER(), nullable=True),
    sa.Column('ammonium_sulphate', sa.INTEGER(), nullable=True),
    sa.Column('bag_of_12X32X16', sa.INTEGER(), nullable=True),
    sa.Column('bag_of_10X26X26', sa.INTEGER(), nullable=True),
    sa.Column('mop', sa.INTEGER(), nullable=True),
    sa.Column('micronutrients', sa.INTEGER(), nullable=True),
    sa.Column('sulphur', sa.INTEGER(), nullable=True),
    sa.Column('bag_of_19X19X19', sa.INTEGER(), nullable=True),
    sa.Column('bag_of_20X20X0X13', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fertilizers')
    # ### end Alembic commands ###
